### PR TITLE
Make compatible with Rails 6 & 7 Zeitwerk loader

### PR DESCRIPTION
**Pull request by overhacked**
Rails 6 & 7 autoloading with Zeitwerk enabled didn't get along with this gem's approach to loading agent gems and adding them to `Agent::TYPES` when the `Agent` model got reloaded.

Add a `Zeitwerk::Loader` for each agent gem that is registered with `Zeitwerk` so that Rails can load `Agents::YOUR_AGENT_CLASS` on demand.

For Rails "classic" autoloader, use `require_dependency` instead of `require` so that the autoloader knows where to reload the agent class from, as recommended in
https://guides.rubyonrails.org/v5.2/autoloading_and_reloading_constants.html#autoloading-and-require

Closes #29 as unneeded.
Needs huginn/huginn#3451 to be merged at the same time.

### CODE REVIEW

**Review by knu — APPROVED** [review]
I'm not absolutely sure if this will work for all huginn agent gems, but let go with it.

**Comment by knu** [comment]
@dsander Can you cut a new release of this gem?  Or I will if you add me as a co-owner.

**Comment by knu** [comment]
@overhacked Do you know how to get the specs to pass?  I wonder how things like `Rails` and `require_dependency` are resolved without loading anything.

**Comment by overhacked** [comment]
I will work on getting the specs to pass. I remember some specifics in the Zeitwerk migration docs about specs, so I’ll go back that direction.

**Comment by dsander** [comment]
@knu I have added you as an owner.

**Pull request merged**
